import React from 'react';
import Head from 'next/head';
import Navbar from './navitems/Navbar';
import { motion, useScroll } from 'framer-motion';

const Layout = ({ children }) => {
  const { scrollYProgress } = useScroll();
  return (
    <div className="bg-[#edf2f8] snap-y snap-mandatory  z-0 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <motion.div
          style={{ scaleX: scrollYProgress }}
          className="fixed inset-0 h-1 opacity-70 bg-[#200e57] origin-[0%] z-50 "
        />
        <main>{children}</main>
      </div>
    </div>
  );
};

export default Layout;
